[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add='autocmd! VimEnter * nested colorscheme codedark'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add='''
let g:alrline_theme = 'codedark'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
execute 'source '.expand('~/.config/nvim/plugins/fern.vim')
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
execute 'source '.expand('~/.config/nvim/plugins/gitgutter.vim')
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
  autocmd VimEnter * RainbowToggle
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
execute 'source '.expand('~/.config/nvim/plugins/coc.vim')
'''
